export const source = [
  {
    id: '1',
    price: '1500',
    name: 'ExeGate',
    formFactor: 'Mini-Tower',
    color: 'black',
    year: '2010',
    externalСoolers: false,
    hullWidth: '180',
  },
  {
    id: '2',
    price: '1600',
    name: 'ExeGate',
    formFactor: 'Mini-Tower',
    color: 'black',
    year: '2011',
    externalСoolers: false,
    hullWidth: '190',
  },
  {
    id: '3',
    price: '1200',
    name: 'ExeGate',
    formFactor: 'Mini-Tower',
    color: 'black',
    year: '2009',
    externalСoolers: false,
    hullWidth: '200',
  },
  {
    id: '4',
    price: '1800',
    name: 'ExeGate',
    formFactor: 'Mid-Tower',
    color: 'black',
    year: '2009',
    externalСoolers: false,
    hullWidth: '200',
  },
  {
    id: '5',
    price: '1850',
    name: 'GiNZZU',
    formFactor: 'Mini-Tower',
    color: 'black',
    year: '2018',
    externalСoolers: false,
    hullWidth: '210',
  },
  {
    id: '6',
    price: '2000',
    name: 'ExeGate',
    formFactor: 'SFF',
    color: 'black',
    year: '2020',
    externalСoolers: false,
    hullWidth: '150',
  },
  {
    id: '7',
    price: '1300',
    name: 'Dexp',
    formFactor: 'Mid-Tower',
    color: 'pink',
    year: '2011',
    externalСoolers: false,
    hullWidth: '200',
  },
  {
    id: '8',
    price: '1400',
    name: 'Dexp',
    formFactor: 'Mid-Tower',
    color: 'blue',
    year: '2011',
    externalСoolers: false,
    hullWidth: '200',
  },
  {
    id: '9',
    price: '2100',
    name: 'Dexp',
    formFactor: 'Mid-Tower',
    color: 'grey',
    year: '2011',
    externalСoolers: false,
    hullWidth: '260',
  },
  {
    id: '10',
    price: '1550',
    name: 'Dexp',
    formFactor: 'Mini-Tower',
    color: 'grey',
    year: '2014',
    externalСoolers: false,
    hullWidth: '230',
  },
  {
    id: '11',
    price: '2000',
    name: 'GINZZU',
    formFactor: 'Mini-Tower',
    color: 'white',
    year: '2015',
    externalСoolers: false,
    hullWidth: '220',
  },
  {
    id: '12',
    price: '2500',
    name: 'GINZZU',
    formFactor: 'Mid-Tower',
    color: 'white',
    year: '2016',
    externalСoolers: false,
    hullWidth: '250',
  },
  {
    id: '13',
    price: '3500',
    name: 'ExeGate',
    formFactor: 'SFF',
    color: 'black',
    year: '2018',
    externalСoolers: false,
    hullWidth: '140',
  },
  {
    id: '14',
    price: '2800',
    name: 'ExeGate',
    formFactor: 'Mini-ITX',
    color: 'black',
    year: '2019',
    externalСoolers: false,
    hullWidth: '130',
  },
  {
    id: '15',
    price: '3200',
    name: 'Cougar',
    formFactor: 'Mini-Tower',
    color: 'black',
    year: '2019',
    externalСoolers: false,
    hullWidth: '230',
  },
  {
    id: '16',
    price: '3200',
    name: 'ExeGate',
    formFactor: 'Mid-Tower',
    color: 'blue',
    year: '2020',
    externalСoolers: true,
    hullWidth: '270',
  },
  {
    id: '17',
    price: '3200',
    name: 'ExeGate',
    formFactor: 'Mid-Tower',
    color: 'red',
    year: '2020',
    externalСoolers: true,
    hullWidth: '270',
  },
  {
    id: '18',
    price: '3600',
    name: 'ZALMAN',
    formFactor: 'Mid-Tower',
    color: 'blue',
    year: '2020',
    externalСoolers: true,
    hullWidth: '280',
  },
  {
    id: '19',
    price: '3750',
    name: 'DEEPCOOL',
    formFactor: 'Mid-Tower',
    color: 'black',
    year: '2017',
    externalСoolers: false,
    hullWidth: '260',
  },
  {
    id: '20',
    price: '3700',
    name: 'AeroCool',
    formFactor: 'Mini-Tower',
    color: 'black',
    year: '2021',
    externalСoolers: true,
    hullWidth: '230',
  },
  {
    id: '21',
    price: '3750',
    name: 'AeroCool',
    formFactor: 'Mid-Tower',
    color: 'white',
    year: '2018',
    externalСoolers: false,
    hullWidth: '260',
  },
  {
    id: '22',
    price: '3800',
    name: 'AeroCool',
    formFactor: 'Mid-Tower',
    color: 'white',
    year: '2016',
    externalСoolers: false,
    hullWidth: '270',
  },
  {
    id: '23',
    price: '3800',
    name: 'AeroCool',
    formFactor: 'Mid-Tower',
    color: 'black',
    year: '2021',
    externalСoolers: true,
    hullWidth: '280',
  },
  {
    id: '24',
    price: '4500',
    name: 'AeroCool',
    formFactor: 'SFF',
    color: 'white',
    year: '2022',
    externalСoolers: false,
    hullWidth: '130',
  },
  {
    id: '25',
    price: '3900',
    name: 'AeroCool',
    formFactor: 'Mid-Tower',
    color: 'black',
    year: '2022',
    externalСoolers: true,
    hullWidth: '280',
  },
  {
    id: '26',
    price: '4000',
    name: 'Cougar',
    formFactor: 'Mini-Tower',
    color: 'white',
    year: '2017',
    externalСoolers: false,
    hullWidth: '210',
  },
  {
    id: '27',
    price: '4000',
    name: 'Cougar',
    formFactor: 'Mini-Tower',
    color: 'white',
    year: '2019',
    externalСoolers: false,
    hullWidth: '220',
  },
  {
    id: '28',
    price: '4100',
    name: 'Formula',
    formFactor: 'Mid-Tower',
    color: 'white',
    year: '2015',
    externalСoolers: false,
    hullWidth: '260',
  },
  {
    id: '29',
    price: '4100',
    name: 'ZALMAN',
    formFactor: 'Mini-Tower',
    color: 'grey',
    year: '2022',
    externalСoolers: false,
    hullWidth: '220',
  },
  {
    id: '30',
    price: '4200',
    name: 'ZET',
    formFactor: 'Mini-Tower',
    color: 'white',
    year: '2022',
    externalСoolers: false,
    hullWidth: '230',
  },
  {
    id: '31',
    price: '36000',
    name: 'Corsair',
    formFactor: 'Full-Tower',
    color: 'black',
    year: '2022',
    externalСoolers: true,
    hullWidth: '330',
  },
];
